import type { Category, Difficulty, Question, QuestionType } from "./types";

let counter = 0;

function q(
  category: Category,
  difficulty: Difficulty,
  question: string,
  options: string[],
  correctAnswer: number | number[],
  explanation: string,
  companyTags: string[] = [],
  type: QuestionType = "mcq",
): Question {
  counter += 1;
  return {
    id: `${category}-${String(counter).padStart(3, "0")}`,
    category,
    difficulty,
    companyTags,
    question,
    options,
    correctAnswer,
    type,
    explanation,
    sourceType: "authored",
  };
}

/* ------------------------------ APTITUDE ------------------------------ */
const aptitude: Question[] = [
  q(
    "aptitude",
    "easy",
    "A train covers 300 km in 5 hours. What is its average speed?",
    ["50 km/h", "60 km/h", "65 km/h", "75 km/h"],
    1,
    "Average speed = distance / time = 300 / 5 = 60 km/h.",
    ["TCS", "Infosys"],
  ),
  q(
    "aptitude",
    "easy",
    "If 18 pens cost ₹540, what is the cost of 7 pens?",
    ["₹190", "₹200", "₹210", "₹220"],
    2,
    "Unit price = 540 / 18 = ₹30. So 7 pens cost 7 × 30 = ₹210.",
    ["Capgemini"],
  ),
  q(
    "aptitude",
    "medium",
    "A shopkeeper marks an item 40% above cost and gives a 25% discount. What is the profit percentage?",
    ["5%", "10%", "12%", "15%"],
    0,
    "Let cost be 100. Marked price = 140. Selling price = 140 × 0.75 = 105. Profit = 5%.",
    ["Deloitte", "Accenture"],
  ),
  q(
    "aptitude",
    "medium",
    "Two pipes fill a tank in 12 and 18 minutes respectively. Working together, how long do they take?",
    ["6.8 min", "7.2 min", "8 min", "9 min"],
    1,
    "Combined rate = 1/12 + 1/18 = 5/36 per minute, so time = 36/5 = 7.2 minutes.",
    ["Infosys"],
  ),
  q(
    "aptitude",
    "medium",
    "The average age of 5 friends is 24. A sixth friend joins and the average becomes 25. How old is the sixth?",
    ["28", "29", "30", "31"],
    2,
    "Total before = 120; total after = 150. The sixth friend is 150 − 120 = 30.",
    ["TCS"],
  ),
  q(
    "aptitude",
    "hard",
    "In how many ways can the letters of APTIVIO be arranged?",
    ["1260", "2520", "5040", "10080"],
    1,
    "APTIVIO has 7 letters with I repeating twice: 7!/2! = 5040/2 = 2520.",
    ["Amazon"],
  ),
  q(
    "aptitude",
    "hard",
    "A sum doubles in 8 years at simple interest. In how many years will it become four times?",
    ["16", "20", "24", "32"],
    2,
    "Doubling means interest equals principal in 8 years, so rate = 12.5%. Four times needs 300% interest = 300/12.5 = 24 years.",
    ["Microsoft"],
  ),
  q(
    "aptitude",
    "easy",
    "What is 15% of 480?",
    ["62", "68", "72", "76"],
    2,
    "10% of 480 is 48 and 5% is 24, so 15% = 72.",
  ),
  q(
    "aptitude",
    "medium",
    "A boat travels 24 km downstream in 2 hours and returns in 3 hours. What is the speed of the stream?",
    ["1 km/h", "2 km/h", "3 km/h", "4 km/h"],
    1,
    "Downstream = 12 km/h, upstream = 8 km/h. Stream = (12 − 8)/2 = 2 km/h.",
    ["Capgemini"],
  ),
  q(
    "aptitude",
    "hard",
    "Select every number below that is divisible by both 3 and 4.",
    ["96", "114", "132", "150"],
    [0, 2],
    "Divisibility by 12 is required. 96 = 12 × 8 and 132 = 12 × 11. 114 and 150 are not multiples of 4.",
    ["Deloitte"],
    "multi",
  ),
  q(
    "aptitude",
    "easy",
    "A rectangle's length is twice its breadth and its perimeter is 72 cm. What is the area?",
    ["216 cm²", "244 cm²", "288 cm²", "324 cm²"],
    2,
    "2(2b + b) = 72 gives b = 12 and length = 24, so area = 288 cm².",
  ),
  q(
    "aptitude",
    "medium",
    "The compound interest on ₹10,000 at 10% per annum for 2 years is ₹2,100.",
    ["True", "False"],
    0,
    "Amount = 10000 × 1.1² = 12,100, so the interest is ₹2,100.",
    ["TCS"],
    "boolean",
  ),
];

/* ------------------------------- VERBAL ------------------------------- */
const verbal: Question[] = [
  q(
    "verbal",
    "easy",
    "Choose the word closest in meaning to CANDID.",
    ["Frank", "Cautious", "Clever", "Cheerful"],
    0,
    "Candid means open and honest in expression, which matches frank.",
    ["Infosys"],
  ),
  q(
    "verbal",
    "easy",
    "Choose the correctly spelt word.",
    ["Recieve", "Receive", "Receeve", "Recive"],
    1,
    "The rule 'i before e except after c' gives receive.",
  ),
  q(
    "verbal",
    "medium",
    "Identify the error: 'Each of the candidates were asked to submit their resume.'",
    ["Each of", "were asked", "to submit", "their resume"],
    1,
    "'Each' is singular, so the verb must be 'was asked'.",
    ["TCS", "Accenture"],
  ),
  q(
    "verbal",
    "medium",
    "Choose the antonym of METICULOUS.",
    ["Careless", "Precise", "Diligent", "Thorough"],
    0,
    "Meticulous means extremely careful, so careless is the opposite.",
  ),
  q(
    "verbal",
    "medium",
    "Fill in the blank: 'The manager insisted ___ reviewing the code before release.'",
    ["for", "on", "at", "with"],
    1,
    "'Insist' is followed by the preposition 'on'.",
    ["Capgemini"],
  ),
  q(
    "verbal",
    "hard",
    "Arrange the sentences into a coherent paragraph.",
    [
      "A start-up first identifies a painful, frequent problem.",
      "It then builds the smallest product that solves that problem.",
      "Early users reveal which features actually matter.",
      "Only then does the team invest in scale.",
    ],
    [0, 1, 2, 3],
    "The logical flow moves from problem discovery to a minimum product, to user feedback, and finally to scaling.",
    ["Deloitte"],
    "order",
  ),
  q(
    "verbal",
    "medium",
    "Choose the option that best replaces the underlined part: 'He is one of those managers who *believes* in transparency.'",
    ["believe", "believing", "has believed", "no change"],
    0,
    "The relative pronoun 'who' refers to 'managers' (plural), so 'believe' is correct.",
    ["Amazon"],
  ),
  q(
    "verbal",
    "easy",
    "Pick the correct idiom meaning 'to do something perfectly on the first attempt'.",
    ["Hit the nail on the head", "Beat around the bush", "Burn the midnight oil", "Bite the bullet"],
    0,
    "Hitting the nail on the head means being exactly right.",
  ),
  q(
    "verbal",
    "hard",
    "Select all grammatically correct sentences.",
    [
      "Neither the intern nor the analysts have finished.",
      "The data suggests that retention is improving.",
      "He don't have access to the dashboard.",
      "Each report was reviewed twice.",
    ],
    [0, 1, 3],
    "Options 1, 2 and 4 follow subject-verb agreement. 'He don't' should be 'He doesn't'.",
    ["Microsoft"],
    "multi",
  ),
  q(
    "verbal",
    "easy",
    "'Concise' and 'verbose' are synonyms.",
    ["True", "False"],
    1,
    "Concise means brief while verbose means wordy, so they are antonyms.",
    [],
    "boolean",
  ),
  q(
    "verbal",
    "medium",
    "In a reading passage, the author's tone is described as 'measured'. This most nearly means:",
    ["Angry", "Balanced and controlled", "Humorous", "Uncertain"],
    1,
    "A measured tone is deliberate, calm and balanced.",
  ),
  q(
    "verbal",
    "hard",
    "Choose the word that completes the analogy: Draft : Manuscript :: Sketch : ___",
    ["Canvas", "Painting", "Pencil", "Gallery"],
    1,
    "A draft becomes a finished manuscript just as a sketch becomes a finished painting.",
    ["Accenture"],
  ),
];

/* --------------------------------- HR --------------------------------- */
const hr: Question[] = [
  q(
    "hr",
    "easy",
    "What is the strongest opening for 'Tell me about yourself' in a campus interview?",
    [
      "A recap of your entire family background",
      "A 60-second arc: current study, one proof project, why this role",
      "A list of every certificate you hold",
      "A joke to break the ice",
    ],
    1,
    "A tight present-past-future arc anchored on one proof point keeps the interviewer engaged and sets up follow-ups you control.",
    ["TCS", "Infosys"],
  ),
  q(
    "hr",
    "medium",
    "Which structure best answers a behavioural question?",
    ["STAR", "SWOT", "PESTLE", "RACI"],
    0,
    "STAR (Situation, Task, Action, Result) keeps behavioural answers concrete and measurable.",
    ["Deloitte", "Accenture"],
  ),
  q(
    "hr",
    "medium",
    "You are asked about your greatest weakness. The best approach is to:",
    [
      "Say you are a perfectionist",
      "Claim you have none",
      "Name a real, non-critical weakness plus the correction you are running",
      "Blame a past team",
    ],
    2,
    "Interviewers test self-awareness. A genuine weakness paired with a concrete corrective action shows maturity.",
    ["Amazon"],
  ),
  q(
    "hr",
    "easy",
    "Asking questions at the end of an interview signals interest and preparation.",
    ["True", "False"],
    0,
    "Thoughtful questions about the team, metrics or ramp-up plan consistently improve interviewer impressions.",
    [],
    "boolean",
  ),
  q(
    "hr",
    "medium",
    "Select the responses that work well for 'Why should we hire you?'",
    [
      "Map two role requirements to evidence from your projects",
      "Say you need a job urgently",
      "Quantify an outcome you personally drove",
      "List your hobbies",
    ],
    [0, 2],
    "Tie yourself to the requirement and prove it with a measurable outcome; personal need and hobbies are irrelevant to the hiring decision.",
    ["Microsoft"],
    "multi",
  ),
  q(
    "hr",
    "hard",
    "Arrange the ideal STAR answer sequence.",
    [
      "Describe the situation and constraint",
      "State the task you owned",
      "Explain the specific actions you took",
      "Close with a quantified result and learning",
    ],
    [0, 1, 2, 3],
    "STAR ends with a measurable result; skipping it is the most common campus-interview mistake.",
    ["Deloitte"],
    "order",
  ),
  q(
    "hr",
    "medium",
    "A TCS interviewer asks about relocation. The safest honest answer is:",
    [
      "Refuse outright",
      "Confirm flexibility if true, and state your genuine constraints if not",
      "Say yes and negotiate later",
      "Avoid the question",
    ],
    1,
    "Service companies staff projects across cities; honest flexibility avoids offer withdrawal later.",
    ["TCS"],
  ),
  q(
    "hr",
    "easy",
    "What should a one-page fresher resume lead with?",
    ["Hobbies", "Declaration", "Skills and projects with impact", "Parents' occupation"],
    2,
    "Recruiters scan for skills and evidence in the first six seconds; declarations and hobbies add no signal.",
    ["Capgemini"],
  ),
  q(
    "hr",
    "hard",
    "You lack one skill listed in the job description. Best response?",
    [
      "Pretend you know it",
      "Acknowledge the gap, show the closest transferable work and your learning plan",
      "Change the subject",
      "Say the skill is not important",
    ],
    1,
    "Honest gap acknowledgement with transferable evidence and a plan outperforms bluffing, which usually collapses in follow-ups.",
    ["Amazon", "Microsoft"],
  ),
  q(
    "hr",
    "medium",
    "In a group discussion, the highest-scoring behaviour is usually:",
    [
      "Speaking the longest",
      "Interrupting to dominate",
      "Structuring the discussion and inviting quieter members",
      "Staying silent to avoid mistakes",
    ],
    2,
    "Evaluators score structure, clarity and collaboration far higher than airtime.",
    ["Accenture"],
  ),
  q(
    "hr",
    "easy",
    "Salary expectations for a fresher role are best answered by:",
    [
      "Quoting a random high number",
      "Citing the published band and expressing flexibility",
      "Refusing to answer",
      "Asking the interviewer to decide entirely",
    ],
    1,
    "Referencing the standard band shows research while flexibility keeps the conversation open.",
  ),
  q(
    "hr",
    "medium",
    "Follow-up email after an interview should be sent within 24 hours.",
    ["True", "False"],
    0,
    "A short, specific thank-you within a day keeps you memorable while decisions are still being made.",
    [],
    "boolean",
  ),
];

/* ------------------------------ TECHNICAL ----------------------------- */
const technical: Question[] = [
  q(
    "technical",
    "easy",
    "What is the time complexity of binary search on a sorted array of n elements?",
    ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    1,
    "Each comparison halves the search space, giving logarithmic time.",
    ["Amazon", "Microsoft"],
  ),
  q(
    "technical",
    "easy",
    "Which SQL clause filters rows after aggregation?",
    ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    1,
    "WHERE filters before grouping; HAVING filters the aggregated groups.",
    ["TCS", "Infosys"],
  ),
  q(
    "technical",
    "medium",
    "In a relational database, which normal form removes partial dependency on a composite key?",
    ["1NF", "2NF", "3NF", "BCNF"],
    1,
    "Second normal form requires every non-key attribute to depend on the whole composite key.",
    ["Capgemini"],
  ),
  q(
    "technical",
    "medium",
    "Which data structure gives O(1) average lookup by key?",
    ["Array", "Linked list", "Hash table", "Binary search tree"],
    2,
    "Hash tables map keys to buckets, giving constant average-time lookup.",
    ["Amazon"],
  ),
  q(
    "technical",
    "medium",
    "Select every statement that is true about HTTP status codes.",
    [
      "200 means the request succeeded",
      "301 is a permanent redirect",
      "404 means a server error",
      "500 indicates a server-side failure",
    ],
    [0, 1, 3],
    "404 is a client error meaning the resource was not found; 5xx codes represent server failures.",
    ["Microsoft"],
    "multi",
  ),
  q(
    "technical",
    "hard",
    "What does this SQL return: SELECT dept, COUNT(*) FROM emp GROUP BY dept HAVING COUNT(*) > 5;",
    [
      "All departments with their headcount",
      "Only departments with more than five employees",
      "The five largest departments",
      "An error",
    ],
    1,
    "HAVING filters groups, so only departments whose count exceeds five are returned.",
    ["Deloitte"],
  ),
  q(
    "technical",
    "easy",
    "In object-oriented programming, overriding happens at runtime and overloading at compile time.",
    ["True", "False"],
    0,
    "Overriding is resolved by dynamic dispatch at runtime; overloading is resolved by signature at compile time.",
    ["TCS"],
    "boolean",
  ),
  q(
    "technical",
    "medium",
    "Which operating-system condition requires mutual exclusion, hold-and-wait, no preemption and circular wait?",
    ["Starvation", "Thrashing", "Deadlock", "Fragmentation"],
    2,
    "Those are Coffman's four necessary conditions for deadlock.",
    ["Infosys"],
  ),
  q(
    "technical",
    "hard",
    "Arrange the steps of a typical request in a three-tier web application.",
    [
      "Browser sends an HTTP request",
      "Application server validates and applies business rules",
      "Database executes the query and returns rows",
      "Server renders the response back to the browser",
    ],
    [0, 1, 2, 3],
    "Presentation, application and data tiers are traversed in order and the response flows back up.",
    ["Accenture"],
    "order",
  ),
  q(
    "technical",
    "medium",
    "Which index type is most useful for speeding up range queries on a date column?",
    ["Hash index", "B-tree index", "Bitmap index", "No index"],
    1,
    "B-tree indexes keep keys ordered, which makes range scans efficient. Hash indexes only serve equality lookups.",
    ["Amazon"],
  ),
  q(
    "technical",
    "hard",
    "What is the output size complexity of a nested loop join over tables of size m and n without indexes?",
    ["O(m + n)", "O(m log n)", "O(m × n)", "O(log mn)"],
    2,
    "Every row of one table is compared with every row of the other, giving quadratic work.",
    ["Microsoft"],
  ),
  q(
    "technical",
    "easy",
    "Which git command creates a new branch and switches to it?",
    ["git branch new", "git switch -c new", "git merge new", "git clone new"],
    1,
    "git switch -c (or the older git checkout -b) creates and checks out the branch in one step.",
    ["Capgemini"],
  ),
];

/* -------------------------- BUSINESS AWARENESS ------------------------- */
const business: Question[] = [
  q(
    "business",
    "easy",
    "What does 'runway' mean for a start-up?",
    [
      "Total revenue earned to date",
      "Months of operation left at the current burn rate",
      "The number of investors on the cap table",
      "The valuation at the last round",
    ],
    1,
    "Runway = cash in bank ÷ monthly net burn, i.e. how long the company survives without new funding.",
    ["Deloitte"],
  ),
  q(
    "business",
    "easy",
    "Which body sets India's repo rate?",
    ["SEBI", "RBI", "NITI Aayog", "IRDAI"],
    1,
    "The Reserve Bank of India's Monetary Policy Committee decides the repo rate.",
    ["TCS"],
  ),
  q(
    "business",
    "medium",
    "A company's gross margin rises while net margin falls. The most likely reason is:",
    [
      "Cheaper raw materials only",
      "Higher operating or interest expenses below the gross line",
      "Lower sales volume",
      "A change in share price",
    ],
    1,
    "Gross margin covers only cost of goods sold; costs such as marketing, salaries and interest sit lower in the P&L and can compress net margin.",
    ["Deloitte", "Accenture"],
  ),
  q(
    "business",
    "medium",
    "In SaaS, what does ARR stand for?",
    ["Average Revenue Rate", "Annual Recurring Revenue", "Adjusted Return Ratio", "Annual Retention Rate"],
    1,
    "ARR is the normalised annual value of recurring subscription contracts.",
    ["Microsoft"],
  ),
  q(
    "business",
    "medium",
    "Select every metric a subscription business should track closely.",
    ["Churn rate", "LTV to CAC ratio", "Office square footage", "Net revenue retention"],
    [0, 1, 3],
    "Churn, LTV:CAC and NRR describe subscription health; office space is not a growth metric.",
    ["Amazon"],
    "multi",
  ),
  q(
    "business",
    "hard",
    "A firm with high operating leverage will see profits swing more sharply with revenue changes.",
    ["True", "False"],
    0,
    "High fixed costs mean each incremental rupee of revenue drops largely to profit — and losses deepen just as fast when revenue falls.",
    ["Deloitte"],
    "boolean",
  ),
  q(
    "business",
    "easy",
    "What is an IPO?",
    [
      "A private funding round",
      "The first sale of a company's shares to the public",
      "A merger of two firms",
      "A debt restructuring",
    ],
    1,
    "An initial public offering lists the company's shares on a stock exchange for public investors.",
    ["Infosys"],
  ),
  q(
    "business",
    "medium",
    "Unit economics is best described as:",
    [
      "Total company revenue",
      "Profit and cost of serving one customer or unit",
      "The market capitalisation",
      "The employee headcount ratio",
    ],
    1,
    "Unit economics isolates contribution margin per customer or order to test whether growth is actually profitable.",
    ["Accenture"],
  ),
  q(
    "business",
    "hard",
    "Arrange a start-up's typical funding stages in order.",
    ["Bootstrapping", "Seed round", "Series A", "Series B and beyond"],
    [0, 1, 2, 3],
    "Founders self-fund, raise seed capital to find product-market fit, then Series A to scale go-to-market, and later rounds to expand.",
    ["Amazon"],
    "order",
  ),
  q(
    "business",
    "medium",
    "GST in India is a:",
    ["Direct tax", "Indirect consumption tax", "Wealth tax", "Customs-only levy"],
    1,
    "Goods and Services Tax is an indirect tax collected at the point of consumption.",
    ["TCS", "Capgemini"],
  ),
  q(
    "business",
    "hard",
    "A company reports positive net profit but negative operating cash flow. The most common explanation is:",
    [
      "It paid a dividend",
      "Receivables and inventory ballooned",
      "It issued new shares",
      "It reduced its debt",
    ],
    1,
    "Profit is accrual-based; if customers have not paid and inventory is piling up, cash leaves the business even as profit is booked.",
    ["Deloitte", "Microsoft"],
  ),
  q(
    "business",
    "easy",
    "What does B2B mean?",
    ["Business to Buyer", "Business to Business", "Brand to Buyer", "Bank to Business"],
    1,
    "B2B companies sell products or services to other businesses rather than to individual consumers.",
  ),
];

export const QUESTION_BANK: Question[] = [
  ...aptitude,
  ...verbal,
  ...hr,
  ...technical,
  ...business,
];

export const QUESTIONS_BY_ID = Object.fromEntries(
  QUESTION_BANK.map((item) => [item.id, item]),
) as Record<string, Question>;

export function byCategory(category: Category) {
  return QUESTION_BANK.filter((item) => item.category === category);
}

/** Deterministic daily set builder — content changes, code does not. */
export function buildDailySet(day: number) {
  const pick = (category: Category, count: number, offset: number) => {
    const pool = byCategory(category);
    return Array.from({ length: count }, (_, i) => {
      const item = pool[(offset + i) % pool.length];
      return item!.id;
    });
  };
  const seed = (day - 1) * 2;
  return {
    day,
    morning: [
      ...pick("business", 2, seed),
      ...pick("aptitude", 2, seed),
      ...pick("verbal", 2, seed),
      ...pick("hr", 2, seed),
      ...pick("technical", 2, seed),
    ],
    evening: [
      ...pick("aptitude", 2, seed + 4),
      ...pick("technical", 3, seed + 4),
      ...pick("verbal", 2, seed + 4),
      ...pick("business", 2, seed + 4),
      ...pick("hr", 1, seed + 4),
    ],
  };
}
